on: push
name: Publish Website over SFTP
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: KruserG/sunsetWeb@v1
      with:
         ftp-server: ftp://ftp.sunsetradio.me/
         ftp-username: sunsetra
         ftp-password: ${{secrets.FTP_PASSWORD}}
         git-ftp-args: --insecure 
